# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdgGrQUzzJpiXc7WmrxJZOqHXbDnu3vA
"""

import matplotlib.pyplot as plt
from google.colab import files

# Загрузка файла
print("📁 Загрузите measurements.csv:")
uploaded = files.upload()

# Получаем имя загруженного файла
filename = list(uploaded.keys())[0]
print(f"✓ Загружен файл: {filename}")

# Читаем файл
with open(filename, 'r') as f:
    content = f.read()

print(f"✓ Размер файла: {len(content)} байт")
print("\nПервые 200 символов:")
print(content[:200])
print("...")

# Парсим данные
data = {}
current = None

for line in content.split('\n'):
    line = line.strip()
    if not line:
        continue

    # Если нет запятых и это не заголовок - это имя структуры
    if ',' not in line and line.lower() not in ['n', 'build_ops', 'avg_query_ops']:
        current = line
        data[current] = {'n': [], 'build': [], 'query': []}
        print(f"✓ Найдена структура: {current}")
        continue

    # Пропускаем заголовки
    if 'n,build_ops' in line.lower():
        continue

    # Читаем данные
    if ',' in line and current:
        parts = line.split(',')
        if len(parts) == 3:
            try:
                data[current]['n'].append(int(parts[0]))
                data[current]['build'].append(int(parts[1]))
                data[current]['query'].append(float(parts[2]))
            except:
                pass

print(f"\n✓ ВСЕГО структур: {len(data)}")
for name, vals in data.items():
    print(f"  • {name}: {len(vals['n'])} точек")

# Строим графики
if len(data) == 0:
    print("\n❌ ОШИБКА: Данные не прочитаны!")
else:
    # График 1: Построение
    plt.figure(figsize=(12, 8))
    for name, vals in data.items():
        if vals['n']:
            plt.plot(vals['n'], vals['build'], 'o-', label=name, linewidth=2, markersize=6)

    plt.xlabel('n', fontsize=12)
    plt.ylabel('Операции построения', fontsize=12)
    plt.title('Сложность ПОСТРОЕНИЯ', fontsize=14, fontweight='bold')
    plt.xscale('log')
    plt.yscale('log')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig('build.png', dpi=300)
    plt.show()

    # График 2: Запросы
    plt.figure(figsize=(12, 8))
    for name, vals in data.items():
        if vals['n']:
            plt.plot(vals['n'], vals['query'], 's-', label=name, linewidth=2, markersize=6)

    plt.xlabel('n', fontsize=12)
    plt.ylabel('Операции на запрос', fontsize=12)
    plt.title('Сложность ЗАПРОСОВ', fontsize=14, fontweight='bold')
    plt.xscale('log')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig('query.png', dpi=300)
    plt.show()

    # Скачиваем
    files.download('build.png')
    files.download('query.png')
    print("\n✅ Готово!")